const loginFields = [
  {
    labelText: "Email address",
    labelFor: "userName",
    id: "userName",
    name: "userName",
    type: "userName",
    autoComplete: "userName",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];

const signupFields = [
  {
    labelText: "Firstname",
    labelFor: "firstName",
    id: "firstName",
    name: "firstName",
    type: "text",
    autoComplete: "firstName",
    isRequired: true,
    placeholder: "Firstname",
  },
  {
    labelText: "Lastname",
    labelFor: "lastName",
    id: "lastName",
    name: "lastName",
    type: "text",
    autoComplete: "lastName",
    isRequired: true,
    placeholder: "Lastname",
  },
  {
    labelText: "Gender",
    labelFor: "gender",
    id: "gender",
    name: "gender",
    type: "text",
    autoComplete: "gender",
    isRequired: true,
    placeholder: "Gender",
  },
  {
    labelText: "Address",
    labelFor: "address",
    id: "address",
    name: "address",
    type: "text",
    autoComplete: "address",
    isRequired: true,
    placeholder: "Address",
  },
  {
    labelText: "Dob",
    labelFor: "dob",
    id: "dob",
    name: "dob",
    type: "date",
    autoComplete: "dob",
    isRequired: true,
    placeholder: "Dob",
  },
  {
    labelText: "Username",
    labelFor: "userName",
    id: "userName",
    name: "userName",
    type: "email",
    autoComplete: "userName",
    isRequired: true,
    placeholder: "UserName",
  },

  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];

export { loginFields, signupFields };
